# Generated by Django 5.0 on 2024-01-05 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0002_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserProfile',
        ),
    ]
