# Generated by Django 5.0 on 2024-01-05 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0003_rename_user_userprofile'),
    ]

    operations = [
    ]
