# Generated by Django 5.0 on 2024-01-05 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0004_auto_20240105_2143'),
    ]

    operations = [
    ]
